# Generated by Django 2.2.1 on 2019-05-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youdao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
